language: java
jdk:
  - oraclejdk8
before_install:
  - cd pet-client
  - "npm install -g npm@^3"
#  - "bower install -g"
node_js: "6"
install: "npm install"
script: 
  - "bower install -g"
  - "npm test"