language: java
jdk:
  - oraclejdk8
before_install:
  - "npm install -g npm@^3"
  - "npm install -g bower"
node_js: "6"
install:
  - "mvn clean install"
script: 
  - cd pet-client
  - "npm install"
  - "bower install"
  - "npm test"
