dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/pet/pet-client/node_modules
  - $HOME/pet/pet-client/bower_components
before_install:
- sudo apt-get remove nodejs
- sudo add-apt-repository -y ppa:chris-lea/node.js
- sudo apt-get -y update
- sudo apt-get -y install nodejs
- apt-cache search node
- npm install -g npm@^3.10.10
- npm install -g bower
- npm install -g phantomjs@^2.1.1
- npm install -g protractor
script:
- node -v
- npm -v
- phantomjs -v
- cd pet-client
